module.exports = {
    "stylesheets": true,
    "size": true,
    "gzippedSize": false,
    "simplicity": true,
    "rules": true,
    "selectors": true,
    "mostIdentifers": true,
    "mostIdentifersSelector": true,
    "lowestCohesion": true,
    "lowestCohesionSelector": true,
    "totalUniqueFontSizes": true,
    "uniqueFontSize": true,
    "totalUniqueColors": true,
    "uniqueColor": true,
    "idSelectors": true,
    "universalSelectors": true,
    "unqualifiedAttributeSelectors": true,
    "javascriptSpecificSelectors": /[#\.]js\-/g,
    "importantKeywords": true,
    "floatProperties": true,
    "mediaQueries": true,
    "propertiesCount": 10
};